//
//  KitStarGuy.m
//  ProjectName
//
//  Created by AuthorName on 6/29/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "KitStarGuy.h"


@implementation KitStarGuy

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawStarGuyWithTopPointX: (CGFloat)topPointX topPointY: (CGFloat)topPointY;
{
    //// Color Declarations
    UIColor* color1 = [UIColor colorWithRed: 0.99 green: 0.5 blue: 0.097 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 0.204 green: 0.589 blue: 0.949 alpha: 1];
    UIColor* color0 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(topPointX, topPointY)];
    [bezierPath addLineToPoint: CGPointMake(208.98, 182.12)];
    [bezierPath addLineToPoint: CGPointMake(318.5, 201.2)];
    [bezierPath addLineToPoint: CGPointMake(239.25, 293.82)];
    [bezierPath addLineToPoint: CGPointMake(257.96, 424.6)];
    [bezierPath addLineToPoint: CGPointMake(160, 362.86)];
    [bezierPath addLineToPoint: CGPointMake(62.04, 424.6)];
    [bezierPath addLineToPoint: CGPointMake(80.75, 293.82)];
    [bezierPath addLineToPoint: CGPointMake(1.5, 201.2)];
    [bezierPath addLineToPoint: CGPointMake(111.02, 182.12)];
    [bezierPath addLineToPoint: CGPointMake(topPointX, topPointY)];
    [bezierPath closePath];
    [color1 setFill];
    [bezierPath fill];
    [color0 setStroke];
    bezierPath.lineWidth = 1;
    [bezierPath stroke];


    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(136.95, 225.55)];
    [bezier2Path addCurveToPoint: CGPointMake(136.95, 261.61) controlPoint1: CGPointMake(146.91, 235.51) controlPoint2: CGPointMake(146.91, 251.65)];
    [bezier2Path addCurveToPoint: CGPointMake(100.89, 261.61) controlPoint1: CGPointMake(127, 271.57) controlPoint2: CGPointMake(110.85, 271.57)];
    [bezier2Path addCurveToPoint: CGPointMake(100.89, 225.55) controlPoint1: CGPointMake(90.94, 251.65) controlPoint2: CGPointMake(90.94, 235.51)];
    [bezier2Path addCurveToPoint: CGPointMake(136.95, 225.55) controlPoint1: CGPointMake(110.85, 215.59) controlPoint2: CGPointMake(127, 215.59)];
    [bezier2Path closePath];
    bezier2Path.miterLimit = 4;

    [color2 setFill];
    [bezier2Path fill];


    //// Bezier 3 Drawing
    UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
    [bezier3Path moveToPoint: CGPointMake(216.95, 225.55)];
    [bezier3Path addCurveToPoint: CGPointMake(216.95, 261.61) controlPoint1: CGPointMake(226.91, 235.51) controlPoint2: CGPointMake(226.91, 251.65)];
    [bezier3Path addCurveToPoint: CGPointMake(180.89, 261.61) controlPoint1: CGPointMake(207, 271.57) controlPoint2: CGPointMake(190.85, 271.57)];
    [bezier3Path addCurveToPoint: CGPointMake(180.89, 225.55) controlPoint1: CGPointMake(170.94, 251.65) controlPoint2: CGPointMake(170.94, 235.51)];
    [bezier3Path addCurveToPoint: CGPointMake(216.95, 225.55) controlPoint1: CGPointMake(190.85, 215.59) controlPoint2: CGPointMake(207, 215.59)];
    [bezier3Path closePath];
    bezier3Path.miterLimit = 4;

    [color2 setFill];
    [bezier3Path fill];
}

@end
