//
//  KitStarGuy.m
//  ProjectName
//
//  Created by AuthorName on 6/29/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "KitStarGuy.h"


@implementation KitStarGuy

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawStarGuyWithPointAX: (CGFloat)pointAX pointAY: (CGFloat)pointAY pointBX: (CGFloat)pointBX pointBY: (CGFloat)pointBY pointCX: (CGFloat)pointCX pointCY: (CGFloat)pointCY pointDX: (CGFloat)pointDX pointDY: (CGFloat)pointDY pointEX: (CGFloat)pointEX pointEY: (CGFloat)pointEY pointFX: (CGFloat)pointFX pointFY: (CGFloat)pointFY pointGX: (CGFloat)pointGX pointGY: (CGFloat)pointGY pointHX: (CGFloat)pointHX pointHY: (CGFloat)pointHY pointIX: (CGFloat)pointIX pointIY: (CGFloat)pointIY pointJX: (CGFloat)pointJX pointJY: (CGFloat)pointJY;
{
    //// Color Declarations
    UIColor* color1 = [UIColor colorWithRed: 0.99 green: 0.5 blue: 0.097 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 0.204 green: 0.589 blue: 0.949 alpha: 1];
    UIColor* color0 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake((pointAX + 1), pointAY)];
    [bezierPath addLineToPoint: CGPointMake(pointBX, pointBY)];
    [bezierPath addLineToPoint: CGPointMake(pointCX, pointCY)];
    [bezierPath addLineToPoint: CGPointMake(pointDX, pointDY)];
    [bezierPath addLineToPoint: CGPointMake(pointEX, pointEY)];
    [bezierPath addLineToPoint: CGPointMake(pointFX, pointFY)];
    [bezierPath addLineToPoint: CGPointMake(pointGX, pointGY)];
    [bezierPath addLineToPoint: CGPointMake(pointHX, pointHY)];
    [bezierPath addLineToPoint: CGPointMake(pointIX, pointIY)];
    [bezierPath addLineToPoint: CGPointMake(pointJX, pointJY)];
    [bezierPath addLineToPoint: CGPointMake((pointAX + 1), pointAY)];
    [bezierPath closePath];
    [color1 setFill];
    [bezierPath fill];
    [color0 setStroke];
    bezierPath.lineWidth = 1;
    [bezierPath stroke];


    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(136.95, 225.55)];
    [bezier2Path addCurveToPoint: CGPointMake(136.95, 261.61) controlPoint1: CGPointMake(146.91, 235.51) controlPoint2: CGPointMake(146.91, 251.65)];
    [bezier2Path addCurveToPoint: CGPointMake(100.89, 261.61) controlPoint1: CGPointMake(127, 271.57) controlPoint2: CGPointMake(110.85, 271.57)];
    [bezier2Path addCurveToPoint: CGPointMake(100.89, 225.55) controlPoint1: CGPointMake(90.94, 251.65) controlPoint2: CGPointMake(90.94, 235.51)];
    [bezier2Path addCurveToPoint: CGPointMake(136.95, 225.55) controlPoint1: CGPointMake(110.85, 215.59) controlPoint2: CGPointMake(127, 215.59)];
    [bezier2Path closePath];
    bezier2Path.miterLimit = 4;

    [color2 setFill];
    [bezier2Path fill];


    //// Bezier 3 Drawing
    UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
    [bezier3Path moveToPoint: CGPointMake(216.95, 225.55)];
    [bezier3Path addCurveToPoint: CGPointMake(216.95, 261.61) controlPoint1: CGPointMake(226.91, 235.51) controlPoint2: CGPointMake(226.91, 251.65)];
    [bezier3Path addCurveToPoint: CGPointMake(180.89, 261.61) controlPoint1: CGPointMake(207, 271.57) controlPoint2: CGPointMake(190.85, 271.57)];
    [bezier3Path addCurveToPoint: CGPointMake(180.89, 225.55) controlPoint1: CGPointMake(170.94, 251.65) controlPoint2: CGPointMake(170.94, 235.51)];
    [bezier3Path addCurveToPoint: CGPointMake(216.95, 225.55) controlPoint1: CGPointMake(190.85, 215.59) controlPoint2: CGPointMake(207, 215.59)];
    [bezier3Path closePath];
    bezier3Path.miterLimit = 4;

    [color2 setFill];
    [bezier3Path fill];
}

@end
