//
//  KitStarGuy.h
//  ProjectName
//
//  Created by WardPenney on 6/29/14.
//  Copyright (c) 2014 WardPenney. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface KitStarGuy : NSObject

// Drawing Methods
+ (void)drawStarGuyWithPointAX: (CGFloat)pointAX pointAY: (CGFloat)pointAY pointBX: (CGFloat)pointBX pointBY: (CGFloat)pointBY pointCX: (CGFloat)pointCX pointCY: (CGFloat)pointCY pointDX: (CGFloat)pointDX pointDY: (CGFloat)pointDY pointEX: (CGFloat)pointEX pointEY: (CGFloat)pointEY pointFX: (CGFloat)pointFX pointFY: (CGFloat)pointFY pointGX: (CGFloat)pointGX pointGY: (CGFloat)pointGY pointHX: (CGFloat)pointHX pointHY: (CGFloat)pointHY pointIX: (CGFloat)pointIX pointIY: (CGFloat)pointIY pointJX: (CGFloat)pointJX pointJY: (CGFloat)pointJY;

@end
