//
//  KitStarGuy.h
//  ProjectName
//
//  Created by AuthorName on 6/29/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface KitStarGuy : NSObject

// Drawing Methods
+ (void)drawStarGuyWithTopPointX: (CGFloat)topPointX topPointY: (CGFloat)topPointY;

@end
